/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp.impl;

import cn.simbaba.mydsl.jp.JpAdditionalVariableDeclaration;
import cn.simbaba.mydsl.jp.JpPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XVariableDeclarationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Additional Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JpAdditionalVariableDeclarationImpl extends XVariableDeclarationImpl implements JpAdditionalVariableDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JpAdditionalVariableDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JpPackage.Literals.JP_ADDITIONAL_VARIABLE_DECLARATION;
  }

} //JpAdditionalVariableDeclarationImpl
