/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp.impl;

import cn.simbaba.mydsl.jp.JpArrayLiteral;
import cn.simbaba.mydsl.jp.JpPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XListLiteralImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Array Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JpArrayLiteralImpl extends XListLiteralImpl implements JpArrayLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JpArrayLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JpPackage.Literals.JP_ARRAY_LITERAL;
  }

} //JpArrayLiteralImpl
