/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp.impl;

import cn.simbaba.mydsl.jp.JpPackage;
import cn.simbaba.mydsl.jp.JpPrefixOperation;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XPostfixOperationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prefix Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JpPrefixOperationImpl extends XPostfixOperationImpl implements JpPrefixOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JpPrefixOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JpPackage.Literals.JP_PREFIX_OPERATION;
  }

} //JpPrefixOperationImpl
