/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp.impl;

import cn.simbaba.mydsl.jp.JpPackage;
import cn.simbaba.mydsl.jp.JpWithOpenCall;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XFeatureCallImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>With Open Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JpWithOpenCallImpl extends XFeatureCallImpl implements JpWithOpenCall
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JpWithOpenCallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JpPackage.Literals.JP_WITH_OPEN_CALL;
  }

} //JpWithOpenCallImpl
