/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp.impl;

import cn.simbaba.mydsl.jp.JpPackage;
import cn.simbaba.mydsl.jp.ScriptBody;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XBlockExpressionImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Script Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScriptBodyImpl extends XBlockExpressionImpl implements ScriptBody
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScriptBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JpPackage.Literals.SCRIPT_BODY;
  }

} //ScriptBodyImpl
