/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractJpScopeProvider extends XbaseBatchScopeProvider {
}
