/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JpUiModule extends AbstractJpUiModule {

	public JpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
