/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JpRuntimeModule extends AbstractJpRuntimeModule {
}
