/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JpStandaloneSetup extends JpStandaloneSetupGenerated {

	public static void doSetup() {
		new JpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
