/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.ide;

import cn.simbaba.mydsl.JpRuntimeModule;
import cn.simbaba.mydsl.JpStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JpIdeSetup extends JpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JpRuntimeModule(), new JpIdeModule()));
	}
	
}
