/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.ui.tests;

import cn.simbaba.mydsl.jp.ui.internal.JpActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class JpUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JpActivator.getInstance().getInjector("cn.simbaba.mydsl.Jp");
	}

}
