/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XVariableDeclaration;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Additional Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpAdditionalVariableDeclaration()
 * @model
 * @generated
 */
public interface JpAdditionalVariableDeclaration extends XVariableDeclaration
{
} // JpAdditionalVariableDeclaration
