/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Dimension</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayDimension()
 * @model
 * @generated
 */
public interface JpArrayDimension extends EObject
{
} // JpArrayDimension
