/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Access Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression#getArray <em>Array</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression#getIndexes <em>Indexes</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayAccessExpression()
 * @model
 * @generated
 */
public interface JpArrayAccessExpression extends XExpression
{
  /**
   * Returns the value of the '<em><b>Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' containment reference.
   * @see #setArray(XExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayAccessExpression_Array()
   * @model containment="true"
   * @generated
   */
  XExpression getArray();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression#getArray <em>Array</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' containment reference.
   * @see #getArray()
   * @generated
   */
  void setArray(XExpression value);

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.xbase.XExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayAccessExpression_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<XExpression> getIndexes();

} // JpArrayAccessExpression
