/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XListLiteral;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayLiteral()
 * @model
 * @generated
 */
public interface JpArrayLiteral extends XListLiteral
{
} // JpArrayLiteral
