/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmType;

import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.xtext.xbase.XListLiteral;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Constructor Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getType <em>Type</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getDimensions <em>Dimensions</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getIndexes <em>Indexes</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getArrayLiteral <em>Array Literal</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayConstructorCall()
 * @model
 * @generated
 */
public interface JpArrayConstructorCall extends XExpression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(JvmType)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayConstructorCall_Type()
   * @model
   * @generated
   */
  JvmType getType();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(JvmType value);

  /**
   * Returns the value of the '<em><b>Dimensions</b></em>' containment reference list.
   * The list contents are of type {@link cn.simbaba.mydsl.jp.JpArrayDimension}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimensions</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayConstructorCall_Dimensions()
   * @model containment="true"
   * @generated
   */
  EList<JpArrayDimension> getDimensions();

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.xbase.XExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayConstructorCall_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<XExpression> getIndexes();

  /**
   * Returns the value of the '<em><b>Array Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Literal</em>' containment reference.
   * @see #setArrayLiteral(XListLiteral)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpArrayConstructorCall_ArrayLiteral()
   * @model containment="true"
   * @generated
   */
  XListLiteral getArrayLiteral();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getArrayLiteral <em>Array Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Literal</em>' containment reference.
   * @see #getArrayLiteral()
   * @generated
   */
  void setArrayLiteral(XListLiteral value);

} // JpArrayConstructorCall
