/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Break Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpBreakStatement()
 * @model
 * @generated
 */
public interface JpBreakStatement extends XExpression
{
} // JpBreakStatement
