/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getIf <em>If</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getThen <em>Then</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpConditionalExpression()
 * @model
 * @generated
 */
public interface JpConditionalExpression extends XExpression
{
  /**
   * Returns the value of the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' containment reference.
   * @see #setIf(XExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpConditionalExpression_If()
   * @model containment="true"
   * @generated
   */
  XExpression getIf();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getIf <em>If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' containment reference.
   * @see #getIf()
   * @generated
   */
  void setIf(XExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(XExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpConditionalExpression_Then()
   * @model containment="true"
   * @generated
   */
  XExpression getThen();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(XExpression value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(XExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpConditionalExpression_Else()
   * @model containment="true"
   * @generated
   */
  XExpression getElse();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(XExpression value);

} // JpConditionalExpression
