/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpElement#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpElement()
 * @model
 * @generated
 */
public interface JpElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // JpElement
