/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xbase.XVariableDeclaration;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Var Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpLetVarDeclaration#getOther <em>Other</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpLetVarDeclaration()
 * @model
 * @generated
 */
public interface JpLetVarDeclaration extends XVariableDeclaration
{
  /**
   * Returns the value of the '<em><b>Other</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.xbase.XVariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpLetVarDeclaration_Other()
   * @model containment="true"
   * @generated
   */
  EList<XVariableDeclaration> getOther();

} // JpLetVarDeclaration
