/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xtype.XImportSection;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpModel#getImportSection <em>Import Section</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpModel#getElements <em>Elements</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpModel#getScripts <em>Scripts</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpModel()
 * @model
 * @generated
 */
public interface JpModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Section</em>' containment reference.
   * @see #setImportSection(XImportSection)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpModel_ImportSection()
   * @model containment="true"
   * @generated
   */
  XImportSection getImportSection();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpModel#getImportSection <em>Import Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Section</em>' containment reference.
   * @see #getImportSection()
   * @generated
   */
  void setImportSection(XImportSection value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link cn.simbaba.mydsl.jp.JpElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<JpElement> getElements();

  /**
   * Returns the value of the '<em><b>Scripts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scripts</em>' containment reference.
   * @see #setScripts(JpScript)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpModel_Scripts()
   * @model containment="true"
   * @generated
   */
  JpScript getScripts();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpModel#getScripts <em>Scripts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scripts</em>' containment reference.
   * @see #getScripts()
   * @generated
   */
  void setScripts(JpScript value);

} // JpModel
