/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xtype.XtypePackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see cn.simbaba.mydsl.jp.JpFactory
 * @model kind="package"
 * @generated
 */
public interface JpPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jp";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.simbaba.cn/mydsl/Jp";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jp";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JpPackage eINSTANCE = cn.simbaba.mydsl.jp.impl.JpPackageImpl.init();

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpModelImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpModel()
   * @generated
   */
  int JP_MODEL = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_MODEL__IMPORT_SECTION = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_MODEL__ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Scripts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_MODEL__SCRIPTS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpScriptImpl <em>Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpScriptImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpScript()
   * @generated
   */
  int JP_SCRIPT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT__AUTHOR = 1;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT__SUPER_TYPE = 2;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT__OPERATIONS = 3;

  /**
   * The feature id for the '<em><b>Script Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT__SCRIPT_BODY = 4;

  /**
   * The number of structural features of the '<em>Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_SCRIPT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpElementImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpElement()
   * @generated
   */
  int JP_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.PackageDeclarationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = JP_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = JP_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = JP_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpClassImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpClass()
   * @generated
   */
  int JP_CLASS = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CLASS__NAME = JP_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CLASS__SUPER_TYPE = JP_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CLASS__FEATURES = JP_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CLASS_FEATURE_COUNT = JP_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.FeatureImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.PropertyImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = FEATURE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = FEATURE__TYPE;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = FEATURE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.OperationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = FEATURE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__TYPE = FEATURE__TYPE;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__PARAMS = FEATURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__BODY = FEATURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = FEATURE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayDimensionImpl <em>Array Dimension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpArrayDimensionImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayDimension()
   * @generated
   */
  int JP_ARRAY_DIMENSION = 8;

  /**
   * The number of structural features of the '<em>Array Dimension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_DIMENSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.ScriptBodyImpl <em>Script Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.ScriptBodyImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getScriptBody()
   * @generated
   */
  int SCRIPT_BODY = 9;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int SCRIPT_BODY__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The number of structural features of the '<em>Script Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT_BODY_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpContinueStatementImpl <em>Continue Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpContinueStatementImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpContinueStatement()
   * @generated
   */
  int JP_CONTINUE_STATEMENT = 10;

  /**
   * The number of structural features of the '<em>Continue Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CONTINUE_STATEMENT_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpBreakStatementImpl <em>Break Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpBreakStatementImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpBreakStatement()
   * @generated
   */
  int JP_BREAK_STATEMENT = 11;

  /**
   * The number of structural features of the '<em>Break Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_BREAK_STATEMENT_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpWithOpenCallImpl <em>With Open Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpWithOpenCallImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpWithOpenCall()
   * @generated
   */
  int JP_WITH_OPEN_CALL = 12;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__FEATURE = XbasePackage.XFEATURE_CALL__FEATURE;

  /**
   * The feature id for the '<em><b>Type Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__TYPE_ARGUMENTS = XbasePackage.XFEATURE_CALL__TYPE_ARGUMENTS;

  /**
   * The feature id for the '<em><b>Implicit Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__IMPLICIT_RECEIVER = XbasePackage.XFEATURE_CALL__IMPLICIT_RECEIVER;

  /**
   * The feature id for the '<em><b>Invalid Feature Issue Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#getInvalidFeatureIssueCode() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_WITH_OPEN_CALL__INVALID_FEATURE_ISSUE_CODE = XbasePackage.XFEATURE_CALL__INVALID_FEATURE_ISSUE_CODE;

  /**
   * The feature id for the '<em><b>Valid Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#isValidFeature() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_WITH_OPEN_CALL__VALID_FEATURE = XbasePackage.XFEATURE_CALL__VALID_FEATURE;

  /**
   * The feature id for the '<em><b>Implicit First Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__IMPLICIT_FIRST_ARGUMENT = XbasePackage.XFEATURE_CALL__IMPLICIT_FIRST_ARGUMENT;

  /**
   * The feature id for the '<em><b>Feature Call Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__FEATURE_CALL_ARGUMENTS = XbasePackage.XFEATURE_CALL__FEATURE_CALL_ARGUMENTS;

  /**
   * The feature id for the '<em><b>Explicit Operation Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__EXPLICIT_OPERATION_CALL = XbasePackage.XFEATURE_CALL__EXPLICIT_OPERATION_CALL;

  /**
   * The feature id for the '<em><b>Type Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__TYPE_LITERAL = XbasePackage.XFEATURE_CALL__TYPE_LITERAL;

  /**
   * The feature id for the '<em><b>Package Fragment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL__PACKAGE_FRAGMENT = XbasePackage.XFEATURE_CALL__PACKAGE_FRAGMENT;

  /**
   * The number of structural features of the '<em>With Open Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_CALL_FEATURE_COUNT = XbasePackage.XFEATURE_CALL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayConstructorCallImpl <em>Array Constructor Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpArrayConstructorCallImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayConstructorCall()
   * @generated
   */
  int JP_ARRAY_CONSTRUCTOR_CALL = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_CONSTRUCTOR_CALL__TYPE = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dimensions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_CONSTRUCTOR_CALL__DIMENSIONS = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_CONSTRUCTOR_CALL__INDEXES = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Array Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_CONSTRUCTOR_CALL__ARRAY_LITERAL = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Array Constructor Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_CONSTRUCTOR_CALL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayLiteralImpl <em>Array Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpArrayLiteralImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayLiteral()
   * @generated
   */
  int JP_ARRAY_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ARRAY_LITERAL__ELEMENTS = XbasePackage.XLIST_LITERAL__ELEMENTS;

  /**
   * The number of structural features of the '<em>Array Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_LITERAL_FEATURE_COUNT = XbasePackage.XLIST_LITERAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayAccessExpressionImpl <em>Array Access Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpArrayAccessExpressionImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayAccessExpression()
   * @generated
   */
  int JP_ARRAY_ACCESS_EXPRESSION = 15;

  /**
   * The feature id for the '<em><b>Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_ACCESS_EXPRESSION__ARRAY = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_ACCESS_EXPRESSION__INDEXES = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Array Access Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ARRAY_ACCESS_EXPRESSION_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpPrefixOperationImpl <em>Prefix Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpPrefixOperationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpPrefixOperation()
   * @generated
   */
  int JP_PREFIX_OPERATION = 16;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION__FEATURE = XbasePackage.XPOSTFIX_OPERATION__FEATURE;

  /**
   * The feature id for the '<em><b>Type Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION__TYPE_ARGUMENTS = XbasePackage.XPOSTFIX_OPERATION__TYPE_ARGUMENTS;

  /**
   * The feature id for the '<em><b>Implicit Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION__IMPLICIT_RECEIVER = XbasePackage.XPOSTFIX_OPERATION__IMPLICIT_RECEIVER;

  /**
   * The feature id for the '<em><b>Invalid Feature Issue Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#getInvalidFeatureIssueCode() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_PREFIX_OPERATION__INVALID_FEATURE_ISSUE_CODE = XbasePackage.XPOSTFIX_OPERATION__INVALID_FEATURE_ISSUE_CODE;

  /**
   * The feature id for the '<em><b>Valid Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#isValidFeature() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_PREFIX_OPERATION__VALID_FEATURE = XbasePackage.XPOSTFIX_OPERATION__VALID_FEATURE;

  /**
   * The feature id for the '<em><b>Implicit First Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION__IMPLICIT_FIRST_ARGUMENT = XbasePackage.XPOSTFIX_OPERATION__IMPLICIT_FIRST_ARGUMENT;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION__OPERAND = XbasePackage.XPOSTFIX_OPERATION__OPERAND;

  /**
   * The number of structural features of the '<em>Prefix Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_PREFIX_OPERATION_FEATURE_COUNT = XbasePackage.XPOSTFIX_OPERATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpIndexImpl <em>Index</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpIndexImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpIndex()
   * @generated
   */
  int JP_INDEX = 17;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_INDEX__INDEXES = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Index</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_INDEX_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpLetVarDeclarationImpl <em>Let Var Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpLetVarDeclarationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpLetVarDeclaration()
   * @generated
   */
  int JP_LET_VAR_DECLARATION = 18;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION__TYPE = XbasePackage.XVARIABLE_DECLARATION__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION__NAME = XbasePackage.XVARIABLE_DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION__RIGHT = XbasePackage.XVARIABLE_DECLARATION__RIGHT;

  /**
   * The feature id for the '<em><b>Writeable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION__WRITEABLE = XbasePackage.XVARIABLE_DECLARATION__WRITEABLE;

  /**
   * The feature id for the '<em><b>Other</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION__OTHER = XbasePackage.XVARIABLE_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Let Var Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_LET_VAR_DECLARATION_FEATURE_COUNT = XbasePackage.XVARIABLE_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpAdditionalVariableDeclarationImpl <em>Additional Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpAdditionalVariableDeclarationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpAdditionalVariableDeclaration()
   * @generated
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION = 19;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION__TYPE = XbasePackage.XVARIABLE_DECLARATION__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION__NAME = XbasePackage.XVARIABLE_DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION__RIGHT = XbasePackage.XVARIABLE_DECLARATION__RIGHT;

  /**
   * The feature id for the '<em><b>Writeable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION__WRITEABLE = XbasePackage.XVARIABLE_DECLARATION__WRITEABLE;

  /**
   * The number of structural features of the '<em>Additional Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ADDITIONAL_VARIABLE_DECLARATION_FEATURE_COUNT = XbasePackage.XVARIABLE_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpWithOpenAsImpl <em>With Open As</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpWithOpenAsImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpWithOpenAs()
   * @generated
   */
  int JP_WITH_OPEN_AS = 20;

  /**
   * The feature id for the '<em><b>Open</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_AS__OPEN = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_AS__NAME = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>With Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_AS__WITH_EXPRESSION = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>With Open As</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_WITH_OPEN_AS_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpImportDeclarationImpl <em>Import Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpImportDeclarationImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpImportDeclaration()
   * @generated
   */
  int JP_IMPORT_DECLARATION = 21;

  /**
   * The feature id for the '<em><b>Wildcard</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__WILDCARD = XtypePackage.XIMPORT_DECLARATION__WILDCARD;

  /**
   * The feature id for the '<em><b>Extension</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__EXTENSION = XtypePackage.XIMPORT_DECLARATION__EXTENSION;

  /**
   * The feature id for the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__STATIC = XtypePackage.XIMPORT_DECLARATION__STATIC;

  /**
   * The feature id for the '<em><b>Imported Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__IMPORTED_TYPE = XtypePackage.XIMPORT_DECLARATION__IMPORTED_TYPE;

  /**
   * The feature id for the '<em><b>Member Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__MEMBER_NAME = XtypePackage.XIMPORT_DECLARATION__MEMBER_NAME;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__IMPORTED_NAMESPACE = XtypePackage.XIMPORT_DECLARATION__IMPORTED_NAMESPACE;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION__ALIAS = XtypePackage.XIMPORT_DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_IMPORT_DECLARATION_FEATURE_COUNT = XtypePackage.XIMPORT_DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpAssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpAssignmentImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpAssignment()
   * @generated
   */
  int JP_ASSIGNMENT = 22;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__FEATURE = XbasePackage.XASSIGNMENT__FEATURE;

  /**
   * The feature id for the '<em><b>Type Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__TYPE_ARGUMENTS = XbasePackage.XASSIGNMENT__TYPE_ARGUMENTS;

  /**
   * The feature id for the '<em><b>Implicit Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__IMPLICIT_RECEIVER = XbasePackage.XASSIGNMENT__IMPLICIT_RECEIVER;

  /**
   * The feature id for the '<em><b>Invalid Feature Issue Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#getInvalidFeatureIssueCode() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_ASSIGNMENT__INVALID_FEATURE_ISSUE_CODE = XbasePackage.XASSIGNMENT__INVALID_FEATURE_ISSUE_CODE;

  /**
   * The feature id for the '<em><b>Valid Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @deprecated See {@link org.eclipse.xtext.xbase.XAbstractFeatureCall#isValidFeature() model documentation} for details.
   * @generated
   * @ordered
   */
  @Deprecated
  int JP_ASSIGNMENT__VALID_FEATURE = XbasePackage.XASSIGNMENT__VALID_FEATURE;

  /**
   * The feature id for the '<em><b>Implicit First Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__IMPLICIT_FIRST_ARGUMENT = XbasePackage.XASSIGNMENT__IMPLICIT_FIRST_ARGUMENT;

  /**
   * The feature id for the '<em><b>Assignable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__ASSIGNABLE = XbasePackage.XASSIGNMENT__ASSIGNABLE;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__VALUE = XbasePackage.XASSIGNMENT__VALUE;

  /**
   * The feature id for the '<em><b>Explicit Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__EXPLICIT_STATIC = XbasePackage.XASSIGNMENT__EXPLICIT_STATIC;

  /**
   * The feature id for the '<em><b>Static With Declaring Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__STATIC_WITH_DECLARING_TYPE = XbasePackage.XASSIGNMENT__STATIC_WITH_DECLARING_TYPE;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT__INDEXES = XbasePackage.XASSIGNMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_ASSIGNMENT_FEATURE_COUNT = XbasePackage.XASSIGNMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cn.simbaba.mydsl.jp.impl.JpConditionalExpressionImpl <em>Conditional Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cn.simbaba.mydsl.jp.impl.JpConditionalExpressionImpl
   * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpConditionalExpression()
   * @generated
   */
  int JP_CONDITIONAL_EXPRESSION = 23;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CONDITIONAL_EXPRESSION__IF = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CONDITIONAL_EXPRESSION__THEN = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CONDITIONAL_EXPRESSION__ELSE = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Conditional Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JP_CONDITIONAL_EXPRESSION_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see cn.simbaba.mydsl.jp.JpModel
   * @generated
   */
  EClass getJpModel();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpModel#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see cn.simbaba.mydsl.jp.JpModel#getImportSection()
   * @see #getJpModel()
   * @generated
   */
  EReference getJpModel_ImportSection();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see cn.simbaba.mydsl.jp.JpModel#getElements()
   * @see #getJpModel()
   * @generated
   */
  EReference getJpModel_Elements();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpModel#getScripts <em>Scripts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scripts</em>'.
   * @see cn.simbaba.mydsl.jp.JpModel#getScripts()
   * @see #getJpModel()
   * @generated
   */
  EReference getJpModel_Scripts();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpScript <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript
   * @generated
   */
  EClass getJpScript();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.JpScript#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript#getName()
   * @see #getJpScript()
   * @generated
   */
  EAttribute getJpScript_Name();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.JpScript#getAuthor <em>Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Author</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript#getAuthor()
   * @see #getJpScript()
   * @generated
   */
  EAttribute getJpScript_Author();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpScript#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Super Type</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript#getSuperType()
   * @see #getJpScript()
   * @generated
   */
  EReference getJpScript_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpScript#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript#getOperations()
   * @see #getJpScript()
   * @generated
   */
  EReference getJpScript_Operations();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpScript#getScriptBody <em>Script Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Script Body</em>'.
   * @see cn.simbaba.mydsl.jp.JpScript#getScriptBody()
   * @see #getJpScript()
   * @generated
   */
  EReference getJpScript_ScriptBody();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see cn.simbaba.mydsl.jp.JpElement
   * @generated
   */
  EClass getJpElement();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.JpElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cn.simbaba.mydsl.jp.JpElement#getName()
   * @see #getJpElement()
   * @generated
   */
  EAttribute getJpElement_Name();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see cn.simbaba.mydsl.jp.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see cn.simbaba.mydsl.jp.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpClass <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see cn.simbaba.mydsl.jp.JpClass
   * @generated
   */
  EClass getJpClass();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpClass#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Super Type</em>'.
   * @see cn.simbaba.mydsl.jp.JpClass#getSuperType()
   * @see #getJpClass()
   * @generated
   */
  EReference getJpClass_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpClass#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see cn.simbaba.mydsl.jp.JpClass#getFeatures()
   * @see #getJpClass()
   * @generated
   */
  EReference getJpClass_Features();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see cn.simbaba.mydsl.jp.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cn.simbaba.mydsl.jp.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see cn.simbaba.mydsl.jp.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Type();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see cn.simbaba.mydsl.jp.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see cn.simbaba.mydsl.jp.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.Operation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see cn.simbaba.mydsl.jp.Operation#getParams()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Params();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.Operation#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see cn.simbaba.mydsl.jp.Operation#getBody()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Body();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpArrayDimension <em>Array Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Dimension</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayDimension
   * @generated
   */
  EClass getJpArrayDimension();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.ScriptBody <em>Script Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script Body</em>'.
   * @see cn.simbaba.mydsl.jp.ScriptBody
   * @generated
   */
  EClass getScriptBody();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpContinueStatement <em>Continue Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Continue Statement</em>'.
   * @see cn.simbaba.mydsl.jp.JpContinueStatement
   * @generated
   */
  EClass getJpContinueStatement();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpBreakStatement <em>Break Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Break Statement</em>'.
   * @see cn.simbaba.mydsl.jp.JpBreakStatement
   * @generated
   */
  EClass getJpBreakStatement();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpWithOpenCall <em>With Open Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With Open Call</em>'.
   * @see cn.simbaba.mydsl.jp.JpWithOpenCall
   * @generated
   */
  EClass getJpWithOpenCall();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall <em>Array Constructor Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Constructor Call</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayConstructorCall
   * @generated
   */
  EClass getJpArrayConstructorCall();

  /**
   * Returns the meta object for the reference '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayConstructorCall#getType()
   * @see #getJpArrayConstructorCall()
   * @generated
   */
  EReference getJpArrayConstructorCall_Type();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getDimensions <em>Dimensions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dimensions</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayConstructorCall#getDimensions()
   * @see #getJpArrayConstructorCall()
   * @generated
   */
  EReference getJpArrayConstructorCall_Dimensions();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayConstructorCall#getIndexes()
   * @see #getJpArrayConstructorCall()
   * @generated
   */
  EReference getJpArrayConstructorCall_Indexes();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpArrayConstructorCall#getArrayLiteral <em>Array Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Array Literal</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayConstructorCall#getArrayLiteral()
   * @see #getJpArrayConstructorCall()
   * @generated
   */
  EReference getJpArrayConstructorCall_ArrayLiteral();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpArrayLiteral <em>Array Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Literal</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayLiteral
   * @generated
   */
  EClass getJpArrayLiteral();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression <em>Array Access Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Access Expression</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayAccessExpression
   * @generated
   */
  EClass getJpArrayAccessExpression();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Array</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayAccessExpression#getArray()
   * @see #getJpArrayAccessExpression()
   * @generated
   */
  EReference getJpArrayAccessExpression_Array();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpArrayAccessExpression#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see cn.simbaba.mydsl.jp.JpArrayAccessExpression#getIndexes()
   * @see #getJpArrayAccessExpression()
   * @generated
   */
  EReference getJpArrayAccessExpression_Indexes();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpPrefixOperation <em>Prefix Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix Operation</em>'.
   * @see cn.simbaba.mydsl.jp.JpPrefixOperation
   * @generated
   */
  EClass getJpPrefixOperation();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Index</em>'.
   * @see cn.simbaba.mydsl.jp.JpIndex
   * @generated
   */
  EClass getJpIndex();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpIndex#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see cn.simbaba.mydsl.jp.JpIndex#getIndexes()
   * @see #getJpIndex()
   * @generated
   */
  EReference getJpIndex_Indexes();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpLetVarDeclaration <em>Let Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Let Var Declaration</em>'.
   * @see cn.simbaba.mydsl.jp.JpLetVarDeclaration
   * @generated
   */
  EClass getJpLetVarDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpLetVarDeclaration#getOther <em>Other</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Other</em>'.
   * @see cn.simbaba.mydsl.jp.JpLetVarDeclaration#getOther()
   * @see #getJpLetVarDeclaration()
   * @generated
   */
  EReference getJpLetVarDeclaration_Other();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpAdditionalVariableDeclaration <em>Additional Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Additional Variable Declaration</em>'.
   * @see cn.simbaba.mydsl.jp.JpAdditionalVariableDeclaration
   * @generated
   */
  EClass getJpAdditionalVariableDeclaration();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpWithOpenAs <em>With Open As</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>With Open As</em>'.
   * @see cn.simbaba.mydsl.jp.JpWithOpenAs
   * @generated
   */
  EClass getJpWithOpenAs();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getOpen <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Open</em>'.
   * @see cn.simbaba.mydsl.jp.JpWithOpenAs#getOpen()
   * @see #getJpWithOpenAs()
   * @generated
   */
  EReference getJpWithOpenAs_Open();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cn.simbaba.mydsl.jp.JpWithOpenAs#getName()
   * @see #getJpWithOpenAs()
   * @generated
   */
  EAttribute getJpWithOpenAs_Name();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getWithExpression <em>With Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>With Expression</em>'.
   * @see cn.simbaba.mydsl.jp.JpWithOpenAs#getWithExpression()
   * @see #getJpWithOpenAs()
   * @generated
   */
  EReference getJpWithOpenAs_WithExpression();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpImportDeclaration <em>Import Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Declaration</em>'.
   * @see cn.simbaba.mydsl.jp.JpImportDeclaration
   * @generated
   */
  EClass getJpImportDeclaration();

  /**
   * Returns the meta object for the attribute '{@link cn.simbaba.mydsl.jp.JpImportDeclaration#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see cn.simbaba.mydsl.jp.JpImportDeclaration#getAlias()
   * @see #getJpImportDeclaration()
   * @generated
   */
  EAttribute getJpImportDeclaration_Alias();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpAssignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see cn.simbaba.mydsl.jp.JpAssignment
   * @generated
   */
  EClass getJpAssignment();

  /**
   * Returns the meta object for the containment reference list '{@link cn.simbaba.mydsl.jp.JpAssignment#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see cn.simbaba.mydsl.jp.JpAssignment#getIndexes()
   * @see #getJpAssignment()
   * @generated
   */
  EReference getJpAssignment_Indexes();

  /**
   * Returns the meta object for class '{@link cn.simbaba.mydsl.jp.JpConditionalExpression <em>Conditional Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Expression</em>'.
   * @see cn.simbaba.mydsl.jp.JpConditionalExpression
   * @generated
   */
  EClass getJpConditionalExpression();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see cn.simbaba.mydsl.jp.JpConditionalExpression#getIf()
   * @see #getJpConditionalExpression()
   * @generated
   */
  EReference getJpConditionalExpression_If();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see cn.simbaba.mydsl.jp.JpConditionalExpression#getThen()
   * @see #getJpConditionalExpression()
   * @generated
   */
  EReference getJpConditionalExpression_Then();

  /**
   * Returns the meta object for the containment reference '{@link cn.simbaba.mydsl.jp.JpConditionalExpression#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see cn.simbaba.mydsl.jp.JpConditionalExpression#getElse()
   * @see #getJpConditionalExpression()
   * @generated
   */
  EReference getJpConditionalExpression_Else();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JpFactory getJpFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpModelImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpModel()
     * @generated
     */
    EClass JP_MODEL = eINSTANCE.getJpModel();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_MODEL__IMPORT_SECTION = eINSTANCE.getJpModel_ImportSection();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_MODEL__ELEMENTS = eINSTANCE.getJpModel_Elements();

    /**
     * The meta object literal for the '<em><b>Scripts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_MODEL__SCRIPTS = eINSTANCE.getJpModel_Scripts();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpScriptImpl <em>Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpScriptImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpScript()
     * @generated
     */
    EClass JP_SCRIPT = eINSTANCE.getJpScript();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JP_SCRIPT__NAME = eINSTANCE.getJpScript_Name();

    /**
     * The meta object literal for the '<em><b>Author</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JP_SCRIPT__AUTHOR = eINSTANCE.getJpScript_Author();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_SCRIPT__SUPER_TYPE = eINSTANCE.getJpScript_SuperType();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_SCRIPT__OPERATIONS = eINSTANCE.getJpScript_Operations();

    /**
     * The meta object literal for the '<em><b>Script Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_SCRIPT__SCRIPT_BODY = eINSTANCE.getJpScript_ScriptBody();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpElementImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpElement()
     * @generated
     */
    EClass JP_ELEMENT = eINSTANCE.getJpElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JP_ELEMENT__NAME = eINSTANCE.getJpElement_Name();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.PackageDeclarationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpClassImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpClass()
     * @generated
     */
    EClass JP_CLASS = eINSTANCE.getJpClass();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_CLASS__SUPER_TYPE = eINSTANCE.getJpClass_SuperType();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_CLASS__FEATURES = eINSTANCE.getJpClass_Features();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.FeatureImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TYPE = eINSTANCE.getFeature_Type();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.PropertyImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.OperationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__PARAMS = eINSTANCE.getOperation_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__BODY = eINSTANCE.getOperation_Body();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayDimensionImpl <em>Array Dimension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpArrayDimensionImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayDimension()
     * @generated
     */
    EClass JP_ARRAY_DIMENSION = eINSTANCE.getJpArrayDimension();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.ScriptBodyImpl <em>Script Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.ScriptBodyImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getScriptBody()
     * @generated
     */
    EClass SCRIPT_BODY = eINSTANCE.getScriptBody();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpContinueStatementImpl <em>Continue Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpContinueStatementImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpContinueStatement()
     * @generated
     */
    EClass JP_CONTINUE_STATEMENT = eINSTANCE.getJpContinueStatement();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpBreakStatementImpl <em>Break Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpBreakStatementImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpBreakStatement()
     * @generated
     */
    EClass JP_BREAK_STATEMENT = eINSTANCE.getJpBreakStatement();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpWithOpenCallImpl <em>With Open Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpWithOpenCallImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpWithOpenCall()
     * @generated
     */
    EClass JP_WITH_OPEN_CALL = eINSTANCE.getJpWithOpenCall();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayConstructorCallImpl <em>Array Constructor Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpArrayConstructorCallImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayConstructorCall()
     * @generated
     */
    EClass JP_ARRAY_CONSTRUCTOR_CALL = eINSTANCE.getJpArrayConstructorCall();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_CONSTRUCTOR_CALL__TYPE = eINSTANCE.getJpArrayConstructorCall_Type();

    /**
     * The meta object literal for the '<em><b>Dimensions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_CONSTRUCTOR_CALL__DIMENSIONS = eINSTANCE.getJpArrayConstructorCall_Dimensions();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_CONSTRUCTOR_CALL__INDEXES = eINSTANCE.getJpArrayConstructorCall_Indexes();

    /**
     * The meta object literal for the '<em><b>Array Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_CONSTRUCTOR_CALL__ARRAY_LITERAL = eINSTANCE.getJpArrayConstructorCall_ArrayLiteral();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayLiteralImpl <em>Array Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpArrayLiteralImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayLiteral()
     * @generated
     */
    EClass JP_ARRAY_LITERAL = eINSTANCE.getJpArrayLiteral();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpArrayAccessExpressionImpl <em>Array Access Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpArrayAccessExpressionImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpArrayAccessExpression()
     * @generated
     */
    EClass JP_ARRAY_ACCESS_EXPRESSION = eINSTANCE.getJpArrayAccessExpression();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_ACCESS_EXPRESSION__ARRAY = eINSTANCE.getJpArrayAccessExpression_Array();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ARRAY_ACCESS_EXPRESSION__INDEXES = eINSTANCE.getJpArrayAccessExpression_Indexes();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpPrefixOperationImpl <em>Prefix Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpPrefixOperationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpPrefixOperation()
     * @generated
     */
    EClass JP_PREFIX_OPERATION = eINSTANCE.getJpPrefixOperation();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpIndexImpl <em>Index</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpIndexImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpIndex()
     * @generated
     */
    EClass JP_INDEX = eINSTANCE.getJpIndex();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_INDEX__INDEXES = eINSTANCE.getJpIndex_Indexes();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpLetVarDeclarationImpl <em>Let Var Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpLetVarDeclarationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpLetVarDeclaration()
     * @generated
     */
    EClass JP_LET_VAR_DECLARATION = eINSTANCE.getJpLetVarDeclaration();

    /**
     * The meta object literal for the '<em><b>Other</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_LET_VAR_DECLARATION__OTHER = eINSTANCE.getJpLetVarDeclaration_Other();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpAdditionalVariableDeclarationImpl <em>Additional Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpAdditionalVariableDeclarationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpAdditionalVariableDeclaration()
     * @generated
     */
    EClass JP_ADDITIONAL_VARIABLE_DECLARATION = eINSTANCE.getJpAdditionalVariableDeclaration();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpWithOpenAsImpl <em>With Open As</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpWithOpenAsImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpWithOpenAs()
     * @generated
     */
    EClass JP_WITH_OPEN_AS = eINSTANCE.getJpWithOpenAs();

    /**
     * The meta object literal for the '<em><b>Open</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_WITH_OPEN_AS__OPEN = eINSTANCE.getJpWithOpenAs_Open();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JP_WITH_OPEN_AS__NAME = eINSTANCE.getJpWithOpenAs_Name();

    /**
     * The meta object literal for the '<em><b>With Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_WITH_OPEN_AS__WITH_EXPRESSION = eINSTANCE.getJpWithOpenAs_WithExpression();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpImportDeclarationImpl <em>Import Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpImportDeclarationImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpImportDeclaration()
     * @generated
     */
    EClass JP_IMPORT_DECLARATION = eINSTANCE.getJpImportDeclaration();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JP_IMPORT_DECLARATION__ALIAS = eINSTANCE.getJpImportDeclaration_Alias();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpAssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpAssignmentImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpAssignment()
     * @generated
     */
    EClass JP_ASSIGNMENT = eINSTANCE.getJpAssignment();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_ASSIGNMENT__INDEXES = eINSTANCE.getJpAssignment_Indexes();

    /**
     * The meta object literal for the '{@link cn.simbaba.mydsl.jp.impl.JpConditionalExpressionImpl <em>Conditional Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cn.simbaba.mydsl.jp.impl.JpConditionalExpressionImpl
     * @see cn.simbaba.mydsl.jp.impl.JpPackageImpl#getJpConditionalExpression()
     * @generated
     */
    EClass JP_CONDITIONAL_EXPRESSION = eINSTANCE.getJpConditionalExpression();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_CONDITIONAL_EXPRESSION__IF = eINSTANCE.getJpConditionalExpression_If();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_CONDITIONAL_EXPRESSION__THEN = eINSTANCE.getJpConditionalExpression_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JP_CONDITIONAL_EXPRESSION__ELSE = eINSTANCE.getJpConditionalExpression_Else();

  }

} //JpPackage
