/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XPostfixOperation;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefix Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpPrefixOperation()
 * @model
 * @generated
 */
public interface JpPrefixOperation extends XPostfixOperation
{
} // JpPrefixOperation
