/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpScript#getName <em>Name</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpScript#getAuthor <em>Author</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpScript#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpScript#getOperations <em>Operations</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpScript#getScriptBody <em>Script Body</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript()
 * @model
 * @generated
 */
public interface JpScript extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpScript#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author</em>' attribute.
   * @see #setAuthor(String)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript_Author()
   * @model
   * @generated
   */
  String getAuthor();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpScript#getAuthor <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author</em>' attribute.
   * @see #getAuthor()
   * @generated
   */
  void setAuthor(String value);

  /**
   * Returns the value of the '<em><b>Super Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' containment reference.
   * @see #setSuperType(JvmParameterizedTypeReference)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript_SuperType()
   * @model containment="true"
   * @generated
   */
  JvmParameterizedTypeReference getSuperType();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpScript#getSuperType <em>Super Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' containment reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(JvmParameterizedTypeReference value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link cn.simbaba.mydsl.jp.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

  /**
   * Returns the value of the '<em><b>Script Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Script Body</em>' containment reference.
   * @see #setScriptBody(XBlockExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpScript_ScriptBody()
   * @model containment="true"
   * @generated
   */
  XBlockExpression getScriptBody();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpScript#getScriptBody <em>Script Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Script Body</em>' containment reference.
   * @see #getScriptBody()
   * @generated
   */
  void setScriptBody(XBlockExpression value);

} // JpScript
