/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.xtext.xbase.XFeatureCall;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>With Open As</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getOpen <em>Open</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getName <em>Name</em>}</li>
 *   <li>{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getWithExpression <em>With Expression</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpWithOpenAs()
 * @model
 * @generated
 */
public interface JpWithOpenAs extends XExpression
{
  /**
   * Returns the value of the '<em><b>Open</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Open</em>' containment reference.
   * @see #setOpen(XFeatureCall)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpWithOpenAs_Open()
   * @model containment="true"
   * @generated
   */
  XFeatureCall getOpen();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getOpen <em>Open</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Open</em>' containment reference.
   * @see #getOpen()
   * @generated
   */
  void setOpen(XFeatureCall value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpWithOpenAs_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>With Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Expression</em>' containment reference.
   * @see #setWithExpression(XExpression)
   * @see cn.simbaba.mydsl.jp.JpPackage#getJpWithOpenAs_WithExpression()
   * @model containment="true"
   * @generated
   */
  XExpression getWithExpression();

  /**
   * Sets the value of the '{@link cn.simbaba.mydsl.jp.JpWithOpenAs#getWithExpression <em>With Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Expression</em>' containment reference.
   * @see #getWithExpression()
   * @generated
   */
  void setWithExpression(XExpression value);

} // JpWithOpenAs
