/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.xtext.xbase.XFeatureCall;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>With Open Call</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getJpWithOpenCall()
 * @model
 * @generated
 */
public interface JpWithOpenCall extends XFeatureCall
{
} // JpWithOpenCall
