/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.simbaba.mydsl.jp.PackageDeclaration#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getPackageDeclaration()
 * @model
 * @generated
 */
public interface PackageDeclaration extends JpElement
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link cn.simbaba.mydsl.jp.JpElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see cn.simbaba.mydsl.jp.JpPackage#getPackageDeclaration_Elements()
   * @model containment="true"
   * @generated
   */
  EList<JpElement> getElements();

} // PackageDeclaration
