/**
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.jp;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cn.simbaba.mydsl.jp.JpPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
