/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.ui;

import cn.simbaba.mydsl.jp.ui.internal.JpActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JpExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JpActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JpActivator activator = JpActivator.getInstance();
		return activator != null ? activator.getInjector(JpActivator.CN_SIMBABA_MYDSL_JP) : null;
	}

}
