/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JpAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cn/simbaba/mydsl/parser/antlr/internal/InternalJp.tokens");
	}
}
