/*
 * generated by Xtext 2.25.0
 */
package cn.simbaba.mydsl.parser.antlr;

import cn.simbaba.mydsl.parser.antlr.internal.InternalJpParser;
import cn.simbaba.mydsl.services.JpGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JpParser extends AbstractAntlrParser {

	@Inject
	private JpGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJpParser createParser(XtextTokenStream stream) {
		return new InternalJpParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JpModel";
	}

	public JpGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JpGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
